spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    url: jdbc:p6spy:mysql:///eblog?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "020922"
  redis:
    host: localhost
    password:
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

file:
  upload:
    dir: ${user.dir}/upload